name: deploy-frontend-s3
on:
  pull_request:
    branches:
      - "main"
    paths:
      - "packages/ui/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "packages/ui"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.17

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy to S3
        uses: reggionick/s3-deploy@v3
        working-directory: "packages/ui"
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: "/"
          delete-removed: true
