name: deploy-frontend-s3

on:
  pull_request:
    branches:
      - main
    paths:
      - packages/ui/**

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    defaults:
      run:
        working-directory: ./packages/ui

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.17

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy to S3
        run: npx s3-deploy@1.4.0 build/**/* --bucket ${{ secrets.S3_BUCKET }} --region ${{ secrets.S3_BUCKET_REGION }} --cwd ./build --distId ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --invalidate "/" --deleteRemoved --etag --gzip xml,html,htm,js,css,ttf,otf,svg,txt
        # uses: vhnam/s3-deploy@master
        # with:
        #   filesToInclude: "build/**/*"
        #   folder: packages/ui/
        #   bucket: ${{ secrets.S3_BUCKET }}
        #   bucket-region: ${{ secrets.S3_BUCKET_REGION }}
        #   dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        #   invalidation: "/"
        #   delete-removed: true
